services:
  loadbalancer:
    image: nginx:alpine
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - service-2
      - service-3
      
  database:
    container_name: database
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cnd-project-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-volume:/var/lib/postgresql/data

  service-1:
    build:
      context: ./Dienst-1
      dockerfile: Dockerfile
    container_name: service-1
    depends_on:
      - database

  service-2:
    build: 
      context: ./Dienst-2
      dockerfile: Dockerfile
    container_name: service-2
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cnd-project-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
  
  service-3:
    build: 
      context: ./Dienst-3
      dockerfile: Dockerfile
    container_name: service-3
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cnd-project-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret

networks:
  default:
    driver: bridge

volumes:
  db-volume:
