apiVersion: v1
name: supermarket-chart
description: A Helm chart for Kubernetes deployments
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: "4.12.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
