apiVersion: v1
kind: Service
metadata:
  name: service-3
  labels:
    app: service-3
spec:
  selector:
    app: service-3
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
